# repo
repo: "/opt/application/admin/nifiAnsible/artifacts"

# jdk
jdk_artifact: "jdk-11.0.13_linux-x64_bin.rpm"
nifi_node_jvm_memory: "1024m"
nifi_java_command: "java"
java_home: "/usr/java/jdk-11.0.13"

# jdbc
jdbc_artifact: "ojdbc11.jar"

#DB configuration
db_user: "RIGHTV"
db_password: "RIGHTV"
db_driver: "oracle.jdbc.driver.OracleDriver"
db_hostname: "172.31.170.107"
db_port: "1521"
db_sid: "DB12c"

#linux tunning
hard_nofile: 900000
soft_nofile: 900000

# nifi
nifi_version: 1.15.3
nifi_major_version: "{{ nifi_version | splitext | first }}"

# nifi installation
nifi_base_dir: "/u/opt/nifi"
nifi_archive_name: "nifi-{{ nifi_version }}-bin.tar.gz"
nifi_user: "nifi"
nifi_group: "{{ nifi_user }}"
nifi_service: "/etc/systemd/system/nifi.service"

nifi_home: "{{ nifi_base_dir }}/nifi-current"
nifi_conf_dir: "{{ nifi_home }}/conf"
nifi_nar_dir: "{{ nifi_home }}/lib"
nifi_work_dir: "{{ nifi_home }}/work"


# whether to restart nifi after making changes
nifi_perform_restart: true

# whether to force a restart, useful if another role has made changes (such as updating a custom nar); default is false
nifi_force_restart: false

# A complete list of IP addresses for each nodes within the nifi cluster
#nifi_nodes_list: []

# extra arg that are useful in expression languages
#nifi_extra_args: []

# List of directories for nifi to look in for additional nars.
#nifi_custom_nars: []

# defaults file / directories for nifi
#nifi_database_repository: "{{ nifi_home }}/database_repository"
#nifi_flowfile_repository: "{{ nifi_home }}/flowfile_repository"
#nifi_content_repositories: ["{{ nifi_home }}/content_repository"]
#nifi_provenance_repositories: ["{{ nifi_home }}/provenance_repository"]
#nifi_run_dir: "{{ nifi_home }}/run"

# NiFi cluster settings
nifi_single_node: true
nifi_web_http_host: 0.0.0.0
nifi_web_http_port: 8090

# NiFi java configuration bootstrap
java_arg_3: "Xmx7g"
java_arg_13: "XX:+UseG1GC"

# NiFi registry configuration
registry_properties: "./conf/database.config"

# Queue swap settings
#nifi_queue_swap_threshold: 20000
#nifi_swap_in_threads: 1
#nifi_swap_out_threads: 4

# Content Repository Settings
#nifi_content_claim_max_flow_files: 100
#nifi_content_claim_max_appendable_size: "10 MB"
#nifi_content_archive_max_retention_period: "12 hours"
#nifi_content_archive_max_usage_percentage: "50%"
#nifi_content_archive_enabled: "false"
#nifi_content_always_sync: "false"

# Provenance Settings
#nifi_provenance_implementation: WriteAheadProvenanceRepository
#nifi_provenance_max_storage_time: "24 hours"
#nifi_provenance_max_storage_size: "1 GB"
#nifi_provenance_rollover_time: "30 mins"
#nifi_provenance_rollover_size: "1 GB"
#nifi_provenance_index_shard_size: "4 GB"
#nifi_provenance_query_threads: 2
#nifi_provenance_index_threads: 8
#nifi_provenance_repository_buffer_size: 100000
#nifi_provenance_indexed_fields: EventType, FlowFileUUID, Filename, ProcessorID, Relationship

# Status repository settings
#nifi_components_status_repository_buffer_size: 1440
#nifi_components_status_snapshot_frequency: "1 min"

# NiFi zookeeper settings
#nifi_zookeeper_servers: []
#nifi_zookeeper_dir: /data/zookeeper
#nifi_state_management_embedded_zookeeper_start: false
#nifi_zookeeper_root_node: "/nifi"
#nifi_zookeeper_session_timeout: "10 seconds"
#nifi_zookeeper_autopurge_purgeInterval: 24
#nifi_zookeeper_autopurge_snapRetainCount: 30

# Security settings

nifi_remote_input_secure: false

#logging
nifi_log_app_file_retention: 10
nifi_log_user_file_retention: 10
nifi_log_boot_file_retention: 10
nifi_log_level_root: INFO
nifi_log_level_org_apache_nifi: INFO
nifi_log_level_org_apache_nifi_processors: WARN
nifi_log_level_org_apache_nifi_processors_standard_LogAttribute: INFO
nifi_log_level_org_apache_nifi_controller_repository: WARN
nifi_log_level_org_apache_nifi_controller_repository_StandardProcessSession: WARN
nifi_log_level_org_apache_nifi_cluster: INFO
nifi_log_level_org_apache_nifi_server_JettyServer: INFO
nifi_log_level_org_eclipse_jetty: INFO
nifi_log_level_org_apache_nifi_web_security: INFO
nifi_log_level_org_apache_nifi_web_api_config: INFO
nifi_log_level_org_apache_nifi_authorization: INFO
nifi_log_level_org_apache_nifi_cluster_authorization: INFO
nifi_log_level_org_apache_nifi_bootstrap: INFO
nifi_log_level_org_apache_nifi_bootstrap_Command: INFO
nifi_log_level_org_apache_nifi_web_filter_RequestLogger: INFO
nifi_log_level_org_wali: WARN
nifi_custom_log_levels: []


# Nifi volume settings
#nifi_mount_volume: false
#nifi_volume_mount_point: /mnt/nifi-volume
#nifi_volume_device: /dev/xvdf
#nifi_volume_fs_type: ext4
#nifi_volume_mount_opts: defaults,discard


