---

- name: get process-group id
  uri:
    url: http://{{ ansible_host }}:{{ nifi_web_http_port }}/nifi-api/flow/process-groups/root
    method: GET
  register: command_out

- name: get process-group
  uri:
    url: http://{{ ansible_host }}:{{ nifi_web_http_port }}/nifi-api/flow/process-groups/{{ command_out.json.processGroupFlow.id }}
    method: GET

- name: update templates
  uri:
    url: http://{{ ansible_host }}:{{ nifi_web_http_port }}/nifi-api/process-groups/{{ command_out.json.processGroupFlow.id }}/templates/upload
    method: POST
    body: "{{ lookup('file','issue.json') }}"
    body_format: json
    

- debug:
    msg: "{{process_group}}"
