---

- name: get process-group id
  uri:
    url: http://{{ ansible_host }}:{{ nifi_web_http_port }}/nifi-api/flow/process-groups/root
    method: GET
  register: command_out

- name: get process-group
  uri:
    url: http://{{ ansible_host }}:{{ nifi_web_http_port }}/nifi-api/flow/process-groups/{{ command_out.json.processGroupFlow.id }}
    method: GET

- name: copy template to NiFi node
  copy:
    src: "{{ repo }}/{{ item }}"
    dest: "/tmp/"
  with_items: "{{ upload_templates }}"

- name: upload template to Nifi
  shell: curl -F template=@{{ item }} http://{{ ansible_host }}:{{ nifi_web_http_port }}/nifi-api/process-groups/{{ command_out.json.processGroupFlow.id }}/templates/upload
  register: response_upload
  args:
    chdir: /tmp
  with_items: "{{ upload_templates }}"
    
- debug:
    msg: "{{ response_upload }}"
